#!/bin/sh

if [ -z "$1" ]
then
        echo "usage $0 problem-number"
        exit 1
fi

w3m -dump www.projecteuler.net/problem=$1  \
    | sed '1,9d;10s/\(.*\)/# \1/;11,14d' \
    | sed 's/Project Euler Copyright Information//'

# Example of problem text
#
#     1	  • About
#     2	  • Register
#     3	  • Problems
#     4	  • Login
#     5	
#     6	RSS FeedUse secure connection
#     7	Project Euler .net
#     8	projecteuler.net
#     9	
#    10	Digit fifth powers
#    11	
#    12	Problem 30
#    13	
#    14	Published on Friday, 8th November 2002, 06:00 pm; Solved by 54297
#    15	
#    16	Surprisingly there are only three numbers that can be written as the sum of
#    17	fourth powers of their digits:
#    18	
#    19	    1634 = 1^4 + 6^4 + 3^4 + 4^4
#    20	    8208 = 8^4 + 2^4 + 0^4 + 8^4
#    21	    9474 = 9^4 + 4^4 + 7^4 + 4^4
#    22	
#    23	As 1 = 1^4 is not a sum it is not included.
#    24	
#    25	The sum of these numbers is 1634 + 8208 + 9474 = 19316.
#    26	
#    27	Find the sum of all the numbers that can be written as the sum of fifth powers
#    28	of their digits.
#    29	
#    30	
#    31	
#    32	Project Euler Copyright Information
#    33	                                                                               
#    34	                                                                               
#    35	                                                                               
#    36	                                                           
