#!/bin/sh

if [ -z $1 ]
then
        echo "usage $0 problem-number"
        exit 1
fi

w3m -dump www.projecteuler.net/problem=$1  | sed '1,9d;10s/\(.*\)/# \1/;11,14d' | sed 's/Project Euler Copyright Information//'
